[project]
name = "reusepython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "cython>=3.1.2",
    "pyrealsense2>=2.56.5.9235",
    "ultralytics>=8.3.177",
]

[tool.uv]
environments  = ["sys_platform == 'win32'"]
